# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 19:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(protocol=b'IPv4')),
                ('mac_address', models.CharField(max_length=30)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('control_enabled', models.BooleanField()),
                ('autonomy_enabled', models.BooleanField()),
                ('object_detection_enabled', models.BooleanField()),
                ('database_enabled', models.BooleanField()),
                ('image', models.ImageField(upload_to=b'')),
                ('owner', models.ForeignKey(default=b'0', on_delete=django.db.models.deletion.CASCADE,
                                            related_name='robot_owner', to=settings.AUTH_USER_MODEL)),
                ('permitted_users', models.ManyToManyField(
                    related_name='robot_permitted_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
