# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        ('missionplanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='supported_platforms',
            field=models.ManyToManyField(
                related_name='mission_supported_platforms', to='fleet.Robot'),
        ),
    ]
