# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 01:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missionplanner', '0003_mission_scheduled_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='estimated_duration',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='robot',
        ),
    ]
