# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missionplanner', '0004_auto_20151221_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
