# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missionplanner', '0005_task_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_duration',
            field=models.CharField(default=b'Unknown', max_length=50),
        ),
    ]
