# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 10:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('missionplanner', '0006_task_estimated_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='creator',
            field=models.ForeignKey(default=b'0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
